-- Migration 013: Add Brian Cox YouTube recommendation index (own + curated external)
UPDATE public.wa_owners
SET youtube_videos = $json$
[
  {
    "title": "Professor Brian Cox: Emergence - a brand new world tour for 2026",
    "url": "https://www.youtube.com/watch?v=Aw07Fye4hOs",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "emergence",
      "brand",
      "new",
      "world",
      "2026"
    ],
    "source": "own"
  },
  {
    "title": "Horizons Tour - Ask Me Anything - Quantum Entanglement",
    "url": "https://www.youtube.com/watch?v=ecznlRG-Qkc",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "entanglement"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Are things getting better or worse ? - Horizons Tour 2022",
    "url": "https://www.youtube.com/watch?v=88c2U5xF1hc",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "things",
      "getting",
      "better",
      "worse",
      "2022"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - The last solar eclipse? Horizons Tour 2022",
    "url": "https://www.youtube.com/watch?v=3AYczNacoC8",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "last",
      "solar",
      "eclipse",
      "2022"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Traveling at the speed of light - Horizons Tour 2022",
    "url": "https://www.youtube.com/watch?v=m7vysBJQuyM",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "traveling",
      "speed",
      "light",
      "2022"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Computer games and orbital mechanics ? Horizons Tour 2022",
    "url": "https://www.youtube.com/watch?v=OLKCDEXrjpM",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "computer",
      "games",
      "orbital",
      "2022"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Space travel in 70 years time ?",
    "url": "https://www.youtube.com/watch?v=lXnB8Id3RQU",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "travel",
      "years"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - How did they get the Lunar Rover to the moon?",
    "url": "https://www.youtube.com/watch?v=lFPedJos_YM",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "lunar",
      "rover",
      "moon"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Best Places to Find Alien Life - Horizons Tour 2022",
    "url": "https://www.youtube.com/watch?v=3mCd057Llf8",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "best",
      "places",
      "find",
      "alien",
      "life",
      "2022"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Moving with the Expanding Universe",
    "url": "https://www.youtube.com/watch?v=eEsmiiedYVQ",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "moving",
      "expanding"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Horizons World Tour 2022",
    "url": "https://www.youtube.com/watch?v=IK9A42iHZDo",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "world",
      "2022"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - On Tour Now",
    "url": "https://www.youtube.com/watch?v=TThN4hlXBEI",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "now"
    ],
    "source": "own"
  },
  {
    "title": "This Is Professor Brian Cox - Horizons World Tour 2022",
    "url": "https://www.youtube.com/watch?v=M_Wy61Tj5Dc",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "world",
      "2022"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Einstein's Happiest Thought",
    "url": "https://www.youtube.com/watch?v=FMeKglqzajc",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "einstein",
      "happiest",
      "thought"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - The Farthest Star in The Galaxy",
    "url": "https://www.youtube.com/watch?v=clAet7oDPsw",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "farthest",
      "star",
      "galaxy"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Donut Holes, Topology and Tour Riders",
    "url": "https://www.youtube.com/watch?v=14FN5DkqlMY",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "donut",
      "topology",
      "riders"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - James Webb Space Telescope",
    "url": "https://www.youtube.com/watch?v=Wb_p8wNWz5o",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "james",
      "webb",
      "telescope"
    ],
    "source": "own"
  },
  {
    "title": "Professor Brian Cox - Ask Me Anything - Gravity",
    "url": "https://www.youtube.com/watch?v=Z7DLcku1GqE",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "gravity"
    ],
    "source": "own"
  },
  {
    "title": "Brian Cox & Robin's Ince's Christmas Compendium of Reason : Royal Albert Hall, Dec 14th 202.",
    "url": "https://www.youtube.com/watch?v=ZuscKWLRoO0",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "robin",
      "ince",
      "christmas",
      "compendium",
      "reason",
      "royal",
      "albert"
    ],
    "source": "own"
  },
  {
    "title": "Join Professor Brian Cox on the North American leg of his Horizons Tour.  Pre-sale starts Oct. 4",
    "url": "https://www.youtube.com/watch?v=qyRmmigebOo",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "join",
      "north",
      "american",
      "leg",
      "pre",
      "sale",
      "starts"
    ],
    "source": "own"
  },
  {
    "title": "Horizons BackStage : Do you have a backstage 'rider' ?",
    "url": "https://www.youtube.com/watch?v=CDa7oWrDBac",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "backstage",
      "rider"
    ],
    "source": "own"
  },
  {
    "title": "Horizons BackStage : Brian asks a question about the Event Horizon of M87",
    "url": "https://www.youtube.com/watch?v=cL8l0mz3qPE",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "backstage",
      "asks",
      "question",
      "event",
      "horizon",
      "m87"
    ],
    "source": "own"
  },
  {
    "title": "Horizons BackStage : What happens when the science gets too complex?",
    "url": "https://www.youtube.com/watch?v=l96HdLVDcLQ",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "backstage",
      "happens",
      "when",
      "gets",
      "too",
      "complex"
    ],
    "source": "own"
  },
  {
    "title": "Joe Rogan Experience #2217 - Brian Cox",
    "url": "https://www.youtube.com/watch?v=Rc7OHXJtWco",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "joe",
      "rogan",
      "experience",
      "2217"
    ],
    "source": "external"
  },
  {
    "title": "Joe Rogan Experience #1233 - Brian Cox",
    "url": "https://www.youtube.com/watch?v=wieRZoJSVtw",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "joe",
      "rogan",
      "experience",
      "1233"
    ],
    "source": "external"
  },
  {
    "title": "Joe Rogan Experience #610 - Brian Cox",
    "url": "https://www.youtube.com/watch?v=QZl3ohphHSE",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "joe",
      "rogan",
      "experience",
      "610"
    ],
    "source": "external"
  },
  {
    "title": "Physicist Brian Cox Shares Latest Progress in Understanding Black Holes",
    "url": "https://www.youtube.com/watch?v=WXWepL0Siao",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "physicist",
      "shares",
      "latest",
      "progress",
      "understanding"
    ],
    "source": "external"
  },
  {
    "title": "Are We The Only Intelligent Life in the Universe?? | Joe Rogan & Brian Cox",
    "url": "https://www.youtube.com/watch?v=p9GNCc_4f8A",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "only",
      "intelligent",
      "life",
      "joe",
      "rogan"
    ],
    "source": "external"
  },
  {
    "title": "Physicist Brian Cox on Wormholes and Time Machines | Joe Rogan",
    "url": "https://www.youtube.com/watch?v=YJGi9EqLwCs",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "physicist",
      "wormholes",
      "machines",
      "joe",
      "rogan"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox on Dark Matter & Dark Energy | Joe Rogan",
    "url": "https://www.youtube.com/watch?v=NVCiuPIeYUM",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "dark",
      "matter",
      "energy",
      "joe",
      "rogan"
    ],
    "source": "external"
  },
  {
    "title": "How We Know Space is Flat | Brian Cox and Joe Rogan",
    "url": "https://www.youtube.com/watch?v=ne3HV9tIITw",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "know",
      "flat",
      "joe",
      "rogan"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox On The Most Terrifying Places In Our Solar System | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=cO87BJbwes4",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "most",
      "terrifying",
      "places",
      "solar",
      "system",
      "earth"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox Finds Life in a Toxic Cave | Wonders Of The Solar System | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=A6nRg9e1tGg",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "finds",
      "life",
      "toxic",
      "cave",
      "wonders",
      "solar",
      "system"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox Explores Saturn's Wobbly Moon | Solar System | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=vDTqfPJD5Hk",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "explores",
      "saturn",
      "wobbly",
      "moon",
      "solar",
      "system",
      "earth"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox: The Next Space Frontier | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=uYdcVRkQBck",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "next",
      "frontier",
      "earth"
    ],
    "source": "external"
  },
  {
    "title": "Nature's Most Astonishing Phenomena | Forces of Nature with Brian Cox | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=Q_Cv9uCWUDg",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "nature",
      "most",
      "astonishing",
      "phenomena",
      "forces",
      "earth"
    ],
    "source": "external"
  },
  {
    "title": "Unlocking Gravity with Brian Cox | Horizon: What on Earth Is Wrong with Gravity? | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=wOvJpgjO8Ww",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "unlocking",
      "gravity",
      "horizon",
      "earth",
      "wrong"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox Investigates Titan Saturn's Largest Moon | Wonders Of The Solar System | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=5ssWYcXL4LE",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "investigates",
      "titan",
      "saturn",
      "largest",
      "moon",
      "wonders",
      "solar"
    ],
    "source": "external"
  },
  {
    "title": "The Astonishing Science of Gravity with Brian Cox | Horizon | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=hJt99qHTsd4",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "astonishing",
      "gravity",
      "horizon",
      "earth"
    ],
    "source": "external"
  },
  {
    "title": "The Thin Blue Line - Wonders of the Solar System - BBC",
    "url": "https://www.youtube.com/watch?v=qwgfU228clE",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "thin",
      "blue",
      "line",
      "wonders",
      "solar",
      "system"
    ],
    "source": "external"
  },
  {
    "title": "The Sun's Energy on Earth | Wonders of the Solar System | BBC Studios",
    "url": "https://www.youtube.com/watch?v=c17t_Pf8vI4",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "sun",
      "energy",
      "earth",
      "wonders",
      "solar",
      "system",
      "studios"
    ],
    "source": "external"
  },
  {
    "title": "Eight Wonders Of Our Solar System | The Planets | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=wkQuOrsgVGY",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "eight",
      "wonders",
      "solar",
      "system",
      "planets",
      "earth"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox Experiences Zero Gravity! | World Space Week - Wonders of the Universe | BBC Studios",
    "url": "https://www.youtube.com/watch?v=PosRfeUoPHM",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "experiences",
      "zero",
      "gravity",
      "world",
      "week",
      "wonders",
      "studios"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox Reaches the Edge of Earth's Atmosphere | Wonders Of The Solar System | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=Iu9iD4sPiic",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "reaches",
      "edge",
      "earth",
      "atmosphere",
      "wonders",
      "solar",
      "system"
    ],
    "source": "external"
  },
  {
    "title": "The Mysteries Behind Our Solar System's Majestic Planets | The Planets | BBC Earth Science",
    "url": "https://www.youtube.com/watch?v=uBJeOvWqNkg",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "mysteries",
      "behind",
      "solar",
      "system",
      "majestic",
      "planets",
      "earth"
    ],
    "source": "external"
  },
  {
    "title": "Death of the Universe | Wonders of the Universe w/ Brian Cox | BBC Studios",
    "url": "https://www.youtube.com/watch?v=Untoik6c_gs",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "death",
      "wonders",
      "studios"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox explains why time travels in one direction - BBC",
    "url": "https://www.youtube.com/watch?v=uQSoaiubuA0",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "explains",
      "travels",
      "one",
      "direction"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox visits the world's biggest vacuum | Human Universe - BBC",
    "url": "https://www.youtube.com/watch?v=E43-CfukEgs",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "visits",
      "world",
      "biggest",
      "vacuum",
      "human"
    ],
    "source": "external"
  },
  {
    "title": "How did life begin on Earth? Professor Brian Cox explains everything! ☀️🌱  BBC",
    "url": "https://www.youtube.com/watch?v=G0GyMvq_Fjg",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "life",
      "begin",
      "earth",
      "explains",
      "everything"
    ],
    "source": "external"
  },
  {
    "title": "Why we need the explorers | Brian Cox",
    "url": "https://www.youtube.com/watch?v=HdwOlk6HIVc",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "need",
      "explorers"
    ],
    "source": "external"
  },
  {
    "title": "CERN's supercollider | Brian Cox",
    "url": "https://www.youtube.com/watch?v=_6uKZWnJLCM",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "cern",
      "supercollider"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox: Why black holes could hold the secret to time and space | Full Interview",
    "url": "https://www.youtube.com/watch?v=KZX_c6zfJ2w",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "could",
      "hold",
      "secret",
      "full",
      "interview"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox: The quantum roots of reality | Full Interview",
    "url": "https://www.youtube.com/watch?v=kO41iURud9c",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "roots",
      "reality",
      "full",
      "interview"
    ],
    "source": "external"
  },
  {
    "title": "Physicist Brian Cox explains quantum physics in 22 minutes",
    "url": "https://www.youtube.com/watch?v=BHEhxPuMmQI",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "physicist",
      "explains",
      "minutes"
    ],
    "source": "external"
  },
  {
    "title": "Why haven’t we found aliens? A physicist shares the most popular theories. | Brian Cox",
    "url": "https://www.youtube.com/watch?v=dTjgrG2UY30",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "haven",
      "found",
      "aliens",
      "physicist",
      "shares",
      "most",
      "popular"
    ],
    "source": "external"
  },
  {
    "title": "Brian Cox on quantum computing and black hole physics",
    "url": "https://www.youtube.com/watch?v=laGXRs9Ce70",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "computing",
      "hole"
    ],
    "source": "external"
  },
  {
    "title": "Are We The Universe’s Way of Knowing Itself? With Brian Cox",
    "url": "https://www.youtube.com/watch?v=tpWaAESy6RE",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "way",
      "knowing",
      "itself"
    ],
    "source": "external"
  },
  {
    "title": "Discussing the Frontier of Particle Physics with Brian Cox",
    "url": "https://www.youtube.com/watch?v=urFIHf5coxE",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "discussing",
      "frontier"
    ],
    "source": "external"
  },
  {
    "title": "Multiverses & Wormholes with Brian Cox & Neil deGrasse Tyson – Cosmic Queries",
    "url": "https://www.youtube.com/watch?v=YFOeXZUlrKY",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "multiverses",
      "wormholes",
      "neil",
      "degrasse",
      "tyson",
      "cosmic",
      "queries"
    ],
    "source": "external"
  },
  {
    "title": "Do Aliens Exist? Professor Brian Cox Answers Your Questions | Honesty Box",
    "url": "https://www.youtube.com/watch?v=0L3Vj56ftWM",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "aliens",
      "exist",
      "answers",
      "questions",
      "honesty",
      "box"
    ],
    "source": "external"
  },
  {
    "title": "Are There Infinite Universes? Brian Cox Explains | LADbible Stories",
    "url": "https://www.youtube.com/watch?v=YHRdbtDMRMg",
    "keywords": [
      "physics",
      "cosmology",
      "quantum",
      "mechanics",
      "space",
      "black",
      "holes",
      "time",
      "universe",
      "science",
      "communication",
      "particle",
      "evolution",
      "there",
      "infinite",
      "universes",
      "explains",
      "ladbible",
      "stories"
    ],
    "source": "external"
  }
]$json$::jsonb
WHERE id = '1d4651eb-5ff1-43e3-a0f3-76528fa32b3e';
